version: '3'

networks:
  static-network:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16

services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: test_db
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: password
    networks:
      static-network:
        ipv4_address: 172.28.1.3

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - 5433:80
    environment:
      PGADMIN_DEFAULT_EMAIL: pguser@postgres.com
      PGADMIN_DEFAULT_PASSWORD: password
    networks:
      static-network:
        ipv4_address: 172.28.1.4

  fastapi:
    image: fastapi:v1
    volumes:
      - ./backend/:/backend/
    command: >
      bash -c "rm -f backend/database.sqlite  && export TIMEFLOW_DEV=true  && uvicorn backend.main:app --reload --port 8002 --host 0.0.0.0"
    ports:
      - 8002:8002
    depends_on:
      - "db"
    env_file:
      - .env
    container_name: fastapi
    stdin_open: true # docker run -i
    tty: true # docker run -t
    networks:
      static-network:
        ipv4_address: 172.28.1.2

  # svelte:
  #   image: sveltekit-docker:latest
  #   # restart: always
  #   volumes:
  #     - ./frontend/:/frontend/
  #   command:
  #     npm run dev -- --host
  #   ports:
  #     - 5173:5173
  #   depends_on:
  #     - "fastapi"
  #   env_file:
  #     - .env
  #   stdin_open: true # docker run -i
  #   tty: true # docker run -t

