version: '3'
networks:
  static-network:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
services:
  fastapi:
    image: fastapi:v1
    volumes:
      - ./backend/:/backend/
    command: >
      bash -c "rm -f backend/database.sqlite  && export TIMEFLOW_DEV=true  && uvicorn backend.main:app --reload --port 8002 --host 0.0.0.0"
    ports:
      - 8002:8002
    container_name: fastapi
    stdin_open: true # docker run -i
    tty: true # docker run -t
    networks:
      static-network:
        ipv4_address: 172.28.1.2
  applications:
    #python3 /applications/main2.py && ls
    image: appflow_apps:v1
    volumes:
      - ./:/applications
    command: >
      bash -c "export TIMEFLOW_DEV=true  && cd /applications && uvicorn main:app --workers 1 --host 0.0.0.0 --port 8001 --reload --ssl-keyfile certs/127.0.0.1-key.pem  --ssl-certfile certs/127.0.0.1.pem  --access-log"
    ports:
      - 8001:8001
    container_name: applications
    networks:
      static-network:
        ipv4_address: 172.28.1.1
