apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-db-sv # Sets service name
  labels: &DbLabels
    {{- include "timeflow.db.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: {{ .Values.db.service.port }} # Sets port to run the postgres application
      targetPort: {{ .Values.db.service.targetPort }}
  selector: *DbLabels
