name: building docker image

on:
  push:
    branches: [charts]
  pull_request:
    types:
      - closed
    branches: [charts]

  workflow_dispatch:

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  REPOSITORY_NAME: ${{ secrets.REPOSITORY_NAME}}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:

      - name: Check out the repo
        uses: actions/checkout@v3

      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}          
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build fastapi image
        uses: docker/build-push-action@v3
        #working-directory:
        run: docker build . -f backend/Dockerfile -t fastapi:$(date +%s)
        # with:
        #   context: .
        #   push: true
        #   tags: user/app:latest

      # - name: Set up Python
      #   uses: actions/setup-python@v2
      #   with:
      #     python-version: "3.x"
      # - name: Install dependencies
      #   run: |
      #     python -m pip install --upgrade pip
      #     python -m pip install pytest
      # - name: run test_add.py
      #   run: |
      #     pytest
